#!/usr/bin/env bash
# VOTEBOT-14: writes VoteBot's production /opt/votebot/.env (the compose file's `env_file`) on the HOST,
# from AWS Secrets Manager plus the committed non-secret defaults in infrastructure/docker/prod.env.defaults.
# Nobody types or pastes a secret, and none ever passes through a note, a ticket or shell history.
#
# Same approach as ddp-sync's infrastructure/render-env.sh, and for the same reason: the host's instance
# role already has secretsmanager:GetSecretValue, so the host resolves the secrets once and the container
# only sees a plain env file. VoteBot's own code is unchanged and has no boto3 dependency.
#
# Secrets (JSON object, snake_case keys; a missing or empty one makes the script fail BEFORE touching .env):
#   votebot/credentials  (VOTEBOT_SECRET_ID):  api_key, openai_api_key, pinecone_api_key
#   ddp-sync/credentials (API_SOURCE_SECRET_ID): rds_openstates_api_key  -> DDP_OPENSTATES_BEARER_TOKEN
#       (the shared api-v3 key, decided 2026-10-06; set API_SOURCE_SECRET_ID= empty to skip, then the
#        votebot secret must hold ddp_openstates_api_key instead)
# Other keys in a secret are ignored: only the names mapped below are ever written.
#
# Idempotent: re-run any time to pick up a rotated secret, then `docker compose ... up -d` (a restart ends
# open chats). The file is written atomically (temp file, then rename) with mode 600 and the invoking user as
# owner, because `docker compose` reads `env_file` as that user. Never prints a value: only key NAMES.
#
# Usage:  infrastructure/render-env.sh [--check] [--out FILE]
#   --check   fetch and validate, print which names would be written, write nothing
#   --out     write somewhere other than <repo>/.env
set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
VOTEBOT_SECRET_ID="${VOTEBOT_SECRET_ID:-votebot/credentials}"
API_SOURCE_SECRET_ID="${API_SOURCE_SECRET_ID-ddp-sync/credentials}"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULTS_FILE="${DEFAULTS_FILE:-$REPO_DIR/infrastructure/docker/prod.env.defaults}"
OUT_FILE="$REPO_DIR/.env"
CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    --out) shift; OUT_FILE="${1:?--out needs a file}" ;;
    *) echo "[render-env] unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

[ -r "$DEFAULTS_FILE" ] || { echo "[render-env] missing $DEFAULTS_FILE" >&2; exit 1; }

echo "[render-env] fetching $VOTEBOT_SECRET_ID..."
VOTEBOT_JSON=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$VOTEBOT_SECRET_ID" --query 'SecretString' --output text)
API_JSON='{}'
USE_API_SOURCE=0
if [ -n "$API_SOURCE_SECRET_ID" ]; then
  echo "[render-env] fetching $API_SOURCE_SECRET_ID (the shared api-v3 key)..."
  API_JSON=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "$API_SOURCE_SECRET_ID" --query 'SecretString' --output text)
  USE_API_SOURCE=1
fi

export VOTEBOT_JSON API_JSON USE_API_SOURCE
python3 - "$OUT_FILE" "$DEFAULTS_FILE" "$CHECK" <<'PYEOF'
import json
import os
import sys
import tempfile

out_file, defaults_file, check = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

votebot = json.loads(os.environ["VOTEBOT_JSON"])
api_source = json.loads(os.environ["API_JSON"])

# (secret, secret key) -> env var name. Only these are ever written.
REQUIRED = [
    (votebot, "api_key", "API_KEY"),
    (votebot, "openai_api_key", "OPENAI_API_KEY"),
    (votebot, "pinecone_api_key", "PINECONE_API_KEY"),
]
# The setting name is historical: with DDP_OPENSTATES_AUTH_HEADER=x-api-key it is sent as X-API-Key.
if os.environ["USE_API_SOURCE"] == "1":
    REQUIRED.append((api_source, "rds_openstates_api_key", "DDP_OPENSTATES_BEARER_TOKEN"))
else:
    REQUIRED.append((votebot, "ddp_openstates_api_key", "DDP_OPENSTATES_BEARER_TOKEN"))

secret_lines, written, missing = [], [], []
for source, key, env_name in REQUIRED:
    value = source.get(key)
    if value in (None, ""):
        missing.append(f"{env_name} (secret key {key})")
        continue
    value = str(value)
    if "\n" in value or "\r" in value:
        sys.exit(f"[render-env] refusing: the value for {env_name} contains a newline")
    secret_lines.append(f"{env_name}={value}\n")
    written.append(env_name)

if missing:
    sys.exit("[render-env] missing or empty, nothing written: " + ", ".join(missing))

with open(defaults_file) as f:
    defaults = f.read()
defaults_names = sorted(
    line.split("=", 1)[0] for line in defaults.splitlines() if "=" in line and not line.lstrip().startswith("#")
)
clash = [n for n in defaults_names if n in written]
if clash:
    sys.exit("[render-env] the defaults file must not define secret names: " + ", ".join(clash))

if check:
    print(f"[render-env] --check OK: would write {len(written)} secret names {sorted(written)} + {len(defaults_names)} defaults to {out_file}")
    sys.exit(0)

body = "# Generated by infrastructure/render-env.sh -- do not edit by hand, do not commit.\n" + defaults
if not body.endswith("\n"):
    body += "\n"
body += "".join(secret_lines)

directory = os.path.dirname(os.path.abspath(out_file))
fd, tmp = tempfile.mkstemp(prefix=".env.", dir=directory)
try:
    os.fchmod(fd, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(body)
    os.replace(tmp, out_file)
except BaseException:
    if os.path.exists(tmp):
        os.unlink(tmp)
    raise
print(f"[render-env] wrote {len(written)} secret names {sorted(written)} + {len(defaults_names)} defaults to {out_file} (mode 600)")
PYEOF
unset VOTEBOT_JSON API_JSON USE_API_SOURCE
